model: "/home/guqiong/Downloads/MiniMax-M3-NVFP4"
host: "0.0.0.0"
port: 8070
tensor-parallel-size: 2
max-model-len: 36000
gpu-memory-utilization: 0.95
trust-remote-code: true
tokenizer-mode: "auto"
served-model-name: "MiniMax-M3-NVFP4"
compilation_config.cudagraph_mode: "FULL_DECODE_ONLY"
enable_prefix_caching: true
enable-chunked-prefill: true
max_num_batched_tokens: 18000
dtype: "bfloat16"
max_num_seqs: 2
compilation_config.mode: "VLLM_COMPILE"
enable-auto-tool-choice: true
# mamba-ssm-cache-dtype: "float16"
# reasoning-parser: "super_v3"
# kv_cache_dtype: "bfloat16"  
# speculative-config: '{"method":"qwen3_next_mtp","num_speculative_tokens":7}'
# tool-call-parser: "minimax_m2"
# reasoning-parser: "minimax_m2_append_think"
# tool-call-parser: glm47
# reasoning-parser: glm45
# tool-call-parser: "kimi_k2"
# reasoning-parser: "kimi_k2" 
# mm-encoder-tp-mode: "data"
# disable-cascade-attn: true
# reasoning-parser: "step3p5" 
# tool-call-parser: "step3p5"  
# reasoning-parser: "qwen3"
# tool-call-parser: "qwen3_coder"
# reasoning-parser: "nemotron_v3"
# reasoning-parser: "gemma4"
# tool-call-parser: "gemma4"
tool-call-parser: minimax_m3 
reasoning-parser: minimax_m3 
block-size: 128
